server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/glms
    username: postgres
    password: postgrespassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect