server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/glms
    username: postgres
    password: postgrespassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true